# ============================================================
# ファイル名: debug_txt_writer.py
#
# 機能説明:
#   SectionMarker によってマークされた TXT v1.5 行を
#   デバッグ用の TXT ファイルとして出力する。
#
#   ・内容は一切変更しない
#   ・行番号を付与し、人間が確認しやすくする
#
# 作成者:RothschildsMa
#
# 作成日:2025-12-24 
# ============================================================

from typing import List
from pathlib import Path


class DebugTxtWriter:
    """
    デバッグ用 TXT 出力クラス（TXT v1.5）
    """

    def write(self, lines: List[str], output_path: str) -> None:
        """
        マーカー付き行をデバッグ用 TXT として出力する。

        :param lines: SectionMarker 出力の行リスト
        :param output_path: 出力先ファイルパス
        """

        if lines is None:
            raise ValueError("入力 lines が None です")

        if not output_path:
            raise ValueError("output_path が指定されていません")

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        with path.open(mode="w", encoding="utf-8") as f:
            self._write_header(f)

            for idx, line in enumerate(lines, start=1):
                line_no = str(idx).zfill(4)
                f.write(f"[{line_no}] {line}\n")

    @staticmethod
    def _write_header(file_obj) -> None:
        """
        デバッグ用ヘッダーを書き込む。
        """

        file_obj.write("# ============================================================\n")
        file_obj.write("# DEBUG TXT OUTPUT\n")
        file_obj.write("# Version : TXT v1.5\n")
        file_obj.write("# Generated By : DebugTxtWriter\n")
        file_obj.write("# ============================================================\n\n")
